server:
  port: ${adminServicePort}

spring:
  application:
    name: ${adminApiModuleName}
  cloud:
    service-registry:
      auto-registration:
        enabled: true
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:${eurekaServerPort}/eureka/

feign:
  hystrix:
    enabled: true

cors:
  cors-registrations:
    - pathPattern: /**
      allowedOrigins: '*'
      allowedMethods: GET,POST,UPDATE,DELETE,PUT,TRACE,OPTIONS
      allowedHeaders: Origin, X-Requested-With, Content-Type, Accept
      exposedHeaders:
      allowCredentials: true
      maxAge: 3600
