server:
  port: ${adminServicePort}

spring:
  application:
    name: ${adminApiModuleName}
  cloud:
    service-registry:
      auto-registration:
        enabled: true
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:${eurekaServerPort}/eureka/

feign:
  hystrix:
    enabled: true
