server:
  port: 8820

spring:
  application:
    name: ${adminApiModuleName}

dubbo:
  application:
    id: ${adminApiModuleName}
    name: ${adminApiModuleName}
    owner:
  protocol:
    id: dubbo
    name: dubbo
  consumer:
    group: ${dubboServiceGroup}
    version: ${dubboServiceVersion}
    timeout: 3000
  registry:
    id: ${dubboServiceProtocol}
    protocol: ${dubboServiceProtocol}
    address: ${dubboRegistryAddress}
    group: dubbo # 对应dubbo-admin的dubbo.properties中的dubbo.registry.group=dubbo，默认是dubbo，不一致的话dubbo-admin上不会显示注册的服务
    version: ${dubboServiceVersion}
    client: curator
  scan:
    base-packages: ${basePackage}.admin.service

cors:
  response:
    headers:
      Access-Control-Allow-Origin: '*'
      Access-Control-Allow-Headers: Origin, X-Requested-With, Content-Type, Accept
      Access-Control-Allow-Methods: GET,POST,UPDATE,DELETE,PUT,TRACE,OPTIONS
      Access-Control-Max-Age: 3600
    url-patterns: /*
