server:
  port: 8820

spring:
  application:
    name: ${adminApiModuleName}

dubbo:
  application:
    id: ${adminApiModuleName}
    name: ${adminApiModuleName}
    owner:
  protocol:
    id: dubbo
    name: dubbo
  consumer:
    group: ${dubboServiceGroup}
    version: ${dubboServiceVersion}
    timeout: 3000
  registry:
    id: ${dubboServiceProtocol}
    protocol: ${dubboServiceProtocol}
    address: ${dubboRegistryAddress}
    group: dubbo # 对应dubbo-admin的dubbo.properties中的dubbo.registry.group=dubbo，默认是dubbo，不一致的话dubbo-admin上不会显示注册的服务
    version: ${dubboServiceVersion}
    client: curator
  scan:
    base-packages: ${basePackage}.admin.service

access:
  control:
    allow-origin: '*'
    allow-headers: GET,POST,UPDATE,DELETE,PUT,TRACE,OPTIONS
    max-age: 3600
    allow-methods: Origin, X-Requested-With, Content-Type, Accept
    url-patterns: /*
