server:
  port: 8820

spring:
  application:
    name: ${adminApiModuleName}

dubbo:
  application:
    id: ${adminApiModuleName}
    name: ${adminApiModuleName}
    owner:
  protocol:
    id: dubbo
    name: dubbo
    port: 20990
  consumer:
    group: ${dubboServiceGroup}
    version: ${dubboServiceVersion}
    timeout: 3000
  registry:
    id: ${dubboServiceProtocol}
    protocol: ${dubboServiceProtocol}
    address: ${dubboRegistryAddress}
    group: dubbo # 对应dubbo-admin的dubbo.properties中的dubbo.registry.group=dubbo，默认是dubbo，不一致的话dubbo-admin上不会显示注册的服务
    version: ${dubboServiceVersion}
    client: curator
  scan:
    base-packages: ${basePackage}.admin.service

cors:
  cors-registrations:
    - pathPattern: /**
      allowedOrigins: '*'
      allowedMethods: GET,POST,UPDATE,DELETE,PUT,TRACE,OPTIONS
      allowedHeaders: Origin, X-Requested-With, Content-Type, Accept
      exposedHeaders:
      allowCredentials: true
      maxAge: 3600
  filter:
    pathPattern: /*
    allowedOrigins: http://localhost:8080
    allowedMethods: GET,POST,UPDATE,DELETE,PUT,TRACE,OPTIONS
    allowedHeaders: Origin, X-Requested-With, Content-Type, Accept
    allowCredentials: true
    maxAge: 3600
