mybatis:
  mapper-locations: classpath:mapper/*.xml
  config-location: classpath:mybatis-config.xml
  type-aliases-package: org.xi.quick.codegenerator.mapper
spring:
  datasource:
    url: jdbc:mysql://192.168.46.141:30111/business_data?
    username: business_data_rw
    password: zelMM2bh62RtFgJ9
    driver-class-name: com.mysql.jdbc.Driver

dollar: $

generator:
  encoding: UTF-8                # 代码字符集
  path:
    template: /Workspace/github.com/java/code-generator/company/template/  # 模版路径
    out: /Workspace/gitee.com/            # 输出路径
  file:
    ignore: include/                                        # 要忽略的文件
    aggregate: ${dollar}{adminWebModuleName}/index.html
    # 聚合文件
    just-copy: resources/bootstrap/, resources/css/, mybatis-config.xml, common.js, .gitignore
    # 仅复制文件
  valid-status-field:                                       # 是否删除字段
    fieldName: is_delete                                   # 字段名
    validValue: 0                                           # 有效值
    invalidValue: 1                                         # 无效值
  fk-select-fields:                                         # 逻辑外键字段，用于前台select生成
  - nameSet: source_terminal_code, region_code, page_type_code, event_type_code, sub_event_type_code, parent_enum_id
    foreignTable: dim_uba_enum
    keyField: enum_id                                          # 对应的关联表外键字段
    valueField: enum_name                            # 对应的关联表外键值
  - nameSet: app_key                                 # 当前表字段名
    table: dim_uba_eventgen
    foreignTable: dim_app                               # 对应的关联表
    keyField: app_key                                          # 对应的关联表外键字段
    valueField: app_name                            # 对应的关联表外键值
  - nameSet: page_id                                 # 当前表字段名
    table: dim_uba_event
    foreignTable: dim_uba_event                               # 对应的关联表
    keyField: page_id                                          # 对应的关联表外键字段
    valueField: page_name                            # 对应的关联表外键值
  - nameSet: app_key                                 # 当前表字段名
    table: dim_uba_page
    foreignTable: dim_app                               # 对应的关联表
    keyField: app_key                                          # 对应的关联表外键字段
    valueField: app_name                            # 对应的关联表外键值
  field:
    not-required: create_time, update_time
    select:
    - nameSet: is_internal_use
      options:
      - value: 0
        text: 否
      - value: 1
        text: 是
    img-url: help_img
    video-url:
    doc-url:
    page-url:
    other-url:
    content: data_json, sdk_code, remark

  # 公共自定义属性
  common-properties:

    projectName: ampmind-data-webserver-auto
    projectShortName: 流量监控系统
    projectGroup: com.chehejia.data
    projectVersion: 0.0.0.2-SNAPSHOT

    basePackage: com.chehejia.data.webanalysis

    adminApiModuleName: ampmind-data-admin-api
    adminWebModuleName: ampmind-data-admin-web

    adminModuleApplicationName: WebAnalysisAdminApplication

    baseApiPath: http://localhost:8820

    author: 郗世豪（xishihao@chehejia.com）
    codeVersion: 1.0
    javaSrc: src.main.java
    javaTestSrc: src.test.java
    resourcesSrc: src.main.resources

  # 获取数据映射关系
  data-type-map:
    tinyint: Integer
    smallint: Integer
    int: Integer
    bigint: Long
    float: Float
    double: Double
    decimal: BigDecimal
    numeric: BigDecimal
    bit: Boolean
    character: Character
    varchar: String
    char: String
    text: String
    date: Date
    datetime: Date
    timestamp: Date
