server:
  port: ${eurekaServerPort}
spring:
  application:
    name: ${eurekaServerModuleName}
eureka:
  client:
    fetchRegistry: false
    registerWithEureka: false
    serviceUrl:
      defaultZone: http://127.0.0.1:${r'${server.port}'}/eureka/
