server:
  port: ${adminServicePort}

spring:
  application:
    name: ${adminApiModuleName}
  cloud:
    service-registry:
      auto-registration:
        enabled: true
eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:${eurekaServerPort}/eureka/

feign:
  hystrix:
    enabled: true

cors:
  response:
    headers:
      Access-Control-Allow-Origin: '*'
      Access-Control-Allow-Headers: Origin, X-Requested-With, Content-Type, Accept
      Access-Control-Allow-Methods: GET,POST,UPDATE,DELETE,PUT,TRACE,OPTIONS
      Access-Control-Max-Age: 3600
    url-patterns: /*
