server:
  port: ${adminServicePort}

spring:
  application:
    name: ${adminModuleName}
  cloud:
    service-registry:
      auto-registration:
        enabled: false
eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:${eurekaServerPort}/eureka/

feign:
  hystrix:
    enabled: true

access:
  control:
    allow-origin: '*'
    allow-headers: GET,POST,UPDATE,DELETE,PUT,TRACE,OPTIONS
    max-age: 3600
    allow-methods: Origin, X-Requested-With, Content-Type, Accept
    url-patterns: /*
